resources:
  - name: S_NpmPublish_6679_001_GitRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: raksha78/xray-pipelines-repo
      branches:
        include: .*
  - name: S_NpmPublish_6679_001_buildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: s_artifactory

pipelines:
  - name: S_NpmPublish_6679_001
    steps:
      - name: S_NpmPublish_6679_001_1
        type: NpmBuild
        configuration:
          affinityGroup: S_NpmPublish_6679_001
          sourceLocation: "tests/npm"
          resolverRepo: "test-automation-npm-remote"
          integrations:
            - name: s_artifactory
          inputResources:
            - name: S_NpmPublish_6679_001_GitRepo
      - name: S_NpmPublish_6679_001_2
        type: NpmPublish
        configuration:
          affinityGroup: S_NpmPublish_6679_001
          autoPublishBuildInfo: true
          deployerRepo: "test-automation-npm-local"
          forceXrayScan: true
          integrations:
            - name: s_artifactory
          inputSteps:
            - name: S_NpmPublish_6679_001_1
          outputResources:
            - name: S_NpmPublish_6679_001_buildInfo
